name = "Thermal"
uuid = "7389ebef-f750-435a-92d2-e0c96a4cbd74"
authors = ["David James <davidabraham@ucla.edu>"]
version = "0.1.0"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Structure = "05ea9c01-7fa4-410e-b8ef-4ef973d27c8d"
